name: Publish blog
on: [push]
env:
  GH_PAGES_BRANCH: master
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt
      - run: invoke artifact
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
  publish:
    runs-on: ubuntu-latest
    needs: build-and-upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://rockstar.github.io
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
