name: Publish blog
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pelican==4.8.0" > requirements.txt
      - name: GitHub Pages Pelican Build Action
        uses: nelsonjchen/gh-pages-pelican-action@0.1.10
