name: Publish blog
on: [push]
env:
  GH_PAGES_BRANCH: master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages Pelican Build Action
        uses: nelsonjchen/gh-pages-pelican-action@0.1.10
